### ISSUE TITLE
[Feat] 친구 리스트 UI 수정

### ISSUE THREAD

**Issue by sangeun99** [WishBunny/Android#46]
## Issue: Feature
[Feat] 친구 리스트 UI 수정

## Description
[Feat] 친구 리스트 UI 수정

## Todo
- [x] 친구 리스트 프로필 / 폰트 등 수정
- [x] 친구 초대 페이지 수정
- [x] 친구 매칭 페이지 수정

## ETC
기타사항
<img width="292" alt="image" src="https://github.com/WishBunny/Android/assets/63828057/d2f334c2-dfe8-4acd-ae74-612861e98e02">

**Comment by sangeun99** [comment]
<img width="250" src="https://github.com/WishBunny/Android/assets/63828057/30774527-af53-4f6b-a219-3707da129c9e">
<img width="250" src="https://github.com/WishBunny/Android/assets/63828057/f629bba5-e8b1-4dfb-826a-a90265f20e9f">
<img width="250" src="https://github.com/WishBunny/Android/assets/63828057/1a6ad886-303f-4e6e-956c-8b6e548512d5">
