### ISSUE TITLE
[Feature] 카카오 아이디로 로그인 초기설정

### ISSUE THREAD

**Issue by sangeun99** [WishBunny/Android#5]
## Issue: Feature
- 카카오 아이디로 로그인 초기설정
## Description
- 카카오 아이디로 로그인 초기설정
## Todo
- [x] 카카오 SDK 초기화
- [x] 카카오 로그인 버튼으로 카카오 인가코드 받아오기

**Comment by sangeun99** [comment]
- [x] `debug.properties`를 이용한 변수 처리 필요
